# Generated by Django 4.1.6 on 2023-02-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0003_alter_category_likes_alter_category_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
    ]
