# Generated by Django 4.1.6 on 2023-02-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0004_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
